name: Update EPG

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download EPG
        run: |
          curl -L "https://iptv-org.github.io/epg/epg.xml.gz" -o epg.xml.gz

      - name: Deploy to gh-pages branch
        run: |
          git init
          git checkout -B gh-pages
          rm -rf *
          cp epg.xml.gz .
          git -c user.name="github-actions" -c user.email="actions@github.com" add epg.xml.gz
          git -c user.name="github-actions" -c user.email="actions@github.com" commit -m "Update EPG"
          git push --force origin gh-pages
